// <auto-generated/>
#nullable enable

{{~ if namespace ~}}
namespace {{ namespace }}
{
{{~ end ~}}
    [System.Runtime.CompilerServices.CompilerGenerated]
    public {{ keyword }} {{ type_name }} : System.IEquatable<{{ type_name }}>, System.IComparable<{{ type_name }}>
    {
        public {{ underlying_type }} Value { get; }

        public {{ type_name }}({{ underlying_type }} value)
        {
            Value = value;
        }

{{~ if is_guid ~}}
        public static {{ type_name }} New() => new {{ type_name }}(System.Guid.NewGuid());
        public static {{ type_name }} Empty => new {{ type_name }}(System.Guid.Empty);

{{~ end ~}}
        public static {{ type_name }} From({{ underlying_type }} value) => new {{ type_name }}(value);

        public bool Equals({{ type_name }} other) => Value.Equals(other.Value);
        public override bool Equals(object? obj) => obj is {{ type_name }} other && Equals(other);
        public override int GetHashCode() => Value.GetHashCode();
        public override string ToString() => Value.ToString();
        public int CompareTo({{ type_name }} other) => Value.CompareTo(other.Value);

        public static bool operator ==({{ type_name }} left, {{ type_name }} right) => left.Equals(right);
        public static bool operator !=({{ type_name }} left, {{ type_name }} right) => !left.Equals(right);

        public static implicit operator {{ underlying_type }}({{ type_name }} id) => id.Value;
        public static explicit operator {{ type_name }}({{ underlying_type }} value) => new {{ type_name }}(value);

#if NET6_0_OR_GREATER
        public static {{ type_name }} Parse(string s) => new {{ type_name }}({{ underlying_type }}.Parse(s));
        public static bool TryParse(string? s, out {{ type_name }} result)
        {
            if ({{ underlying_type }}.TryParse(s, out var value))
            {
                result = new {{ type_name }}(value);
                return true;
            }
            result = default;
            return false;
        }
#endif
    }
{{~ if namespace ~}}
}
{{~ end ~}}
